from .count_in_list import count_in_list

# the line below is used to silence the flake8 error impoted but unused
count_in_list(["toto", "tata", "toto"], "toto")
